name: Automerge

on: [pull_request]

env:
    MASTER_BRANCH: master
    MASTER_REPO: https://github.com/ryanschuhler/system-setup.git
    TRANSLATION_BRANCH: test

jobs:
    merge:
        runs-on: ubuntu-latest
        steps:
            - name: Merge with master
              run: |
                  git clone ${{env.MASTER_REPO}} -b ${{env.TRANSLATION_BRANCH}} tmp
                  cd tmp
                  git config user.name "Liferay Translation"
                  git config user.email "lta@liferay.com"
                  git config pull.rebase false
                  git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
                  git push
            - name: Delete branch
              run: |
                  git branch --delete ${{env.MY_BRANCH}}
